services:
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:latest
        env_file: ../config/.env
        ports:
            - "8000:80"
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        networks:
            - net
        restart: always

volumes:
    pgadmin_data:
