env: "dev" # {"dev", "prod"}

storage:
    dsn: "./data/storage.sqlite"

http_server:
    address: "localhost:8080"
    timeout: 5s
    idle_timeout: 60s

logger:
    level: "debug" # {"debug", "info", "warn", "err"}
